yamlConfig: "/config/run.yaml"

vllm:
  url: "https://llama-3-1-8b-instruct-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com:443/v1"
  inferenceModel: "meta-llama/Llama-3.1-8B-Instruct"
  apiKey: 
  # This is the API key for the VLLM server. It can be set in two ways through a secret:
  # TODO: Implement this
  # secret:
  #   name: vllm-secret
  #   key: vll
  # or directly with an api key (should be avoided in production)
  apiKey: "2b24a13694a14f31290680bc1e7b962d"

replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: quay.io/jland/distribution-remote-vllm
  tag: latest
  # This sets the pull policy for images.
  pullPolicy: Always

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 5001

route:
  # -- Enable creation of the OpenShift Route object
  enabled: true
  # Allow OCP to determine the host if left blank
  # -- The hostname for the route
  # @default -- Set by OpenShift
  host: ""
  # -- The path for the OpenShift route
  path: ""
  tls:
    # -- Enable secure route settings
    enabled: true
    # -- Secure route termination policy
    termination: edge
    # -- Insecure route termination policy
    insecureEdgeTerminationPolicy: Redirect
  # -- Additional custom annotations for the route
  annotations: {}


resources:
  limits:
    cpu: 100m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 500Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /v1/health
    port: 5001
readinessProbe:
  httpGet:
    path: /v1/health
    port: 5001
startupProbe:
  httpGet:
    path: /v1/health
    port: 5001
  initialDelaySeconds: 40
  periodSeconds: 10
  failureThreshold: 30

playground:
  enabled: false
  backend:
    url: "https://llama-stack-llama-stack.apps.rhsaia.vg6c.p1.openshiftapps.com"
  replicaCount: 1
  image:
    repository: quay.io/jland/llama-stack-playground
    tag: latest
    # This sets the pull policy for images.
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8501

  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    annotations: {}

  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 500Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe:
    httpGet:
      path: /
      port: 8501
  readinessProbe:
    httpGet:
      path: /
      port: 8501
  startupProbe:
    httpGet:
      path: /
      port: 8501
    initialDelaySeconds: 5
    periodSeconds: 2
    failureThreshold: 16

mcp:
  replicaCount: 1
  image:
    repository: quay.io/hayesphilip/mcp-weather
    tag: latest
    # This sets the pull policy for images.
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000

  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 500Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe:
    httpGet:
      path: /
      port: 8000
  readinessProbe:
    httpGet:
      path: /
      port: 8000
  startupProbe:
    httpGet:
      path: /
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 2
    failureThreshold: 16
